"""create operation_logs_archive

Revision ID: 524ab172e659
Revises: b7d2e9a4c6f8
Create Date: 2026-09-15 12:16:20.496000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '524ab172e659'
down_revision: Union[str, None] = 'b7d2e9a4c6f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_logs_archive',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_operation_logs_archive_resource', 'operation_logs_archive', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_operation_logs_archive_user_archived', 'operation_logs_archive', ['user_id', 'archived_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_operation_logs_archive_user_archived', table_name='operation_logs_archive')
    op.drop_index('ix_operation_logs_archive_resource', table_name='operation_logs_archive')
    op.drop_table('operation_logs_archive')
    # ### end Alembic commands ###
