"""create tasks table

Revision ID: 6f1cfcc35abe
Revises: 99f70df5d269
Create Date: 2026-09-13 23:56:45.306409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f1cfcc35abe'
down_revision: Union[str, None] = '99f70df5d269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='TODO', nullable=False),
    sa.Column('priority', sa.String(length=10), server_default='MEDIUM', nullable=False),
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('LOW', 'MEDIUM', 'HIGH', 'URGENT')", name='ck_tasks_priority_values'),
    sa.CheckConstraint("status IN ('TODO', 'IN_PROGRESS', 'REVIEW', 'DONE', 'CANCELLED')", name='ck_tasks_status_values'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_creator_id'), 'tasks', ['creator_id'], unique=False)
    op.create_index('ix_tasks_due_at_open', 'tasks', ['due_at'], unique=False, postgresql_where="status IN ('TODO', 'IN_PROGRESS', 'REVIEW')")
    op.create_index('ix_tasks_project_id_status', 'tasks', ['project_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_project_id_status', table_name='tasks')
    op.drop_index('ix_tasks_due_at_open', table_name='tasks', postgresql_where="status IN ('TODO', 'IN_PROGRESS', 'REVIEW')")
    op.drop_index(op.f('ix_tasks_creator_id'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
